# Generated by Django 5.1 on 2024-09-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='productos_p_nombre_456643_idx'),
        ),
    ]
