# Generated by Django 5.1 on 2024-09-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_unique_together_alter_producto_stock_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('categoria', 'nombre'), name='categoria_nombre'),
        ),
    ]
